// ==========================================
// DADOS DOS ANIMAIS
// ==========================================
const dadosAnimais = {
    mamiferos: [
        { nome: "Onça-pintada", imagem: "images/mamifero/onca_pintada.jpg", texto: "A onça-pintada é um grande felino encontrado em diferentes regiões da América do Sul e é conhecida por sua força e habilidade como predadora. No Pantanal, vive principalmente em matas ciliares, margens de rios e florestas densas. É carnívora e se alimenta de animais como capivaras, jacarés, veados e queixadas.", curiosidade: "Onça-pintada e ariranha: apesar de serem animais muito diferentes, os dois estão bastante ligados aos ambientes aquáticos. A onça-pintada é uma excelente nadadora e pode caçar dentro da água, enquanto a ariranha passa grande parte de sua vida nos rios." },
        { nome: "Ariranha", imagem: "images/mamifero/ariranha.jpg", texto: "A ariranha é um mamífero aquático muito sociável, conhecido por viver em grupos e passar grande parte do tempo na água. Habita rios calmos, corixos, lagos e margens onde constrói suas tocas. Sua alimentação é principalmente baseada em peixes, como traíras e piranhas.", curiosidade: "A ariranha passa grande parte de sua vida nos rios e é uma excelente nadadora." },
        { nome: "Cervo-do-pantanal", imagem: "images/mamifero/cervo_do_pantanal.jpg", texto: "O cervo-do-pantanal é um mamífero herbívoro adaptado a ambientes alagados. Vive em áreas permanentemente inundadas, brejos e locais com vegetação alta. Alimenta-se principalmente de plantas aquáticas, gramíneas e brotos.", curiosidade: "Cervo-do-pantanal e capivara: os dois são frequentemente encontrados próximos a ambientes alagados." },
        { nome: "Capivara", imagem: "images/mamifero/capivara.jpg", texto: "A capivara é um mamífero roedor que costuma viver em grupos e possui grande adaptação à vida próxima da água. É encontrada nas margens de rios, lagos, banhados e campos úmidos. Sua alimentação é herbívora e inclui grama, capim e plantas aquáticas.", curiosidade: "O cervo-do-pantanal possui adaptações para caminhar em áreas úmidas, enquanto a capivara utiliza a água como local de proteção." },
        { nome: "Anta-brasileira", imagem: "images/mamifero/anta_brasileira.jpg", texto: "A anta-brasileira é um mamífero de grande porte que desempenha um importante papel na dispersão de sementes. Vive em florestas tropicais, matas de galeria e áreas próximas à água. Alimenta-se de folhas, frutos, brotos e cascas de árvores.", curiosidade: "Anta-brasileira e tamanduá-bandeira: a anta ajuda a espalhar sementes pela floresta ao consumir frutos, enquanto o tamanduá contribui para o controle das populações de formigas e cupins." },
        { nome: "Tamanduá-bandeira", imagem: "images/mamifero/tamandua_bandeira.jpg", texto: "O tamanduá-bandeira é um mamífero conhecido pelo focinho comprido e pela língua especializada em capturar insetos. Vive em campos abertos, savanas, cerrados e áreas mais secas. Sua alimentação é baseada principalmente em formigas e cupins.", curiosidade: "O tamanduá contribui para o controle das populações de formigas e cupins." },
        { nome: "Lobo-guará", imagem: "images/mamifero/lobo_guara.jpg", texto: "O lobo-guará é um mamífero de aparência característica, com pernas longas e pelagem avermelhada. Habita campos limpos, cerrados e capinzais secos. É onívoro e se alimenta de pequenos roedores, aves, insetos e frutos, especialmente a lobeira.", curiosidade: "Lobo-guará e jaguatirica: o lobo-guará possui uma alimentação mais variada, incluindo frutos, enquanto a jaguatirica depende principalmente da caça de outros animais." },
        { nome: "Jaguatirica", imagem: "images/mamifero/jaguatirica.jpg", texto: "A jaguatirica é um felino de médio porte que possui uma pelagem cheia de manchas, ajudando na camuflagem. Vive em matas fechadas, capoeiras e florestas de galeria. É carnívora e caça pequenos mamíferos, aves, lagartos e outros animais.", curiosidade: "Lobo-guará e jaguatirica: enquanto o lobo-guará tem dieta variada, a jaguatirica depende da caça." },
        { nome: "Veado-campeiro", imagem: "images/mamifero/veado_campeiro.jpg", texto: "O veado-campeiro é um cervídeo que prefere ambientes abertos e possui hábitos principalmente terrestres. Vive em campos abertos e savanas com bastante vegetação rasteira. É herbívoro e se alimenta de folhas tenras, arbustos e gramíneas.", curiosidade: "Veado-campeiro e queixada: o veado-campeiro costuma ocupar áreas mais abertas, enquanto a queixada prefere ambientes florestais." },
        { nome: "Queixada", imagem: "images/mamifero/queixada.jpg", texto: "A queixada é um mamífero social que costuma viver em grandes bandos e percorrer grandes áreas em busca de alimento. Habita principalmente florestas densas e matas ciliares. É onívora e come frutos, sementes, raízes, brotos e pequenos invertebrados.", curiosidade: "Veado-campeiro e queixada: ambos podem percorrer grandes áreas em busca de alimento." },
        { nome: "Mão-pelada", imagem: "images/mamifero/mao_pelada.jpg", texto: "O mão-pelada é um mamífero de hábitos principalmente noturnos e bastante adaptado a ambientes próximos da água. Vive em margens de rios, áreas úmidas e manguezais. É onívoro e pode se alimentar de caranguejos, sapos, peixes, insetos e frutos.", curiosidade: "Mão-pelada e quati: ambos utilizam o focinho e as patas para procurar diferentes tipos de alimento no ambiente." },
        { nome: "Quati", imagem: "images/mamifero/quati.jpg", texto: "O quati é um mamífero conhecido pelo focinho comprido e pela cauda longa, que pode ser mantida erguida enquanto ele se desloca. Vive em florestas de galeria, matas secas e também utiliza as copas das árvores. É onívoro e come frutos, insetos, aranhas, ovos e pequenos vertebrados.", curiosidade: "Mão-pelada e quati: os dois são parentes e possuem hábitos alimentares bastante variados." },
        { nome: "Bugio-preto", imagem: "images/mamifero/bugio_preto.jpg", texto: "O bugio-preto é um primata que vive principalmente nas partes mais altas das árvores. Habita copas de florestas, matas ciliares e cerradões. Sua alimentação é principalmente herbívora, composta por folhas, flores e frutos.", curiosidade: "Bugio-preto e macaco-prego: o bugio alimenta-se principalmente de folhas e frutos, enquanto o macaco-prego possui uma dieta mais diversificada." },
        { nome: "Macaco-prego", imagem: "images/mamifero/macaco_prego.jpg", texto: "O macaco-prego é um primata bastante inteligente e conhecido pela capacidade de utilizar objetos como ferramentas. Vive em florestas de galeria, matas secas e áreas de transição. É onívoro e se alimenta de frutos, sementes, ovos, insetos e pequenos lagartos.", curiosidade: "Bugio-preto e macaco-prego: ambos são primatas, mas possuem estratégias diferentes para conseguir alimento." },
        { nome: "Tatu-canastra", imagem: "images/mamifero/tatu_canastra.jpg", texto: "O tatu-canastra é um mamífero de hábitos principalmente noturnos e possui grandes garras adaptadas para escavar. Vive em campos abertos, cerrados e locais com solo adequado para a construção de tocas. Alimenta-se principalmente de grandes quantidades de formigas e cupins.", curiosidade: "Tatu-canastra e tatu-galinha: ambos possuem carapaça e são excelentes escavadores. A principal diferença é o tamanho." },
        { nome: "Lontra-neotropical", imagem: "images/mamifero/lontra_neotropical.jpg", texto: "A lontra-neotropical é um mamífero semiaquático que passa bastante tempo procurando alimento na água. Vive em rios, riachos e lagos com vegetação nas margens. É carnívora e piscívora, alimentando-se de peixes, crustáceos e pequenos anfíbios.", curiosidade: "Lontra-neotropical e irara: a lontra é especializada na vida próxima à água, enquanto a irara consegue explorar tanto o solo quanto as árvores." },
        { nome: "Irara", imagem: "images/mamifero/irara.jpg", texto: "A irara é um mamífero ágil que consegue se movimentar tanto no solo quanto nas árvores. Vive em florestas densas e áreas de mata fechada. É onívora e sua alimentação inclui frutos, pequenos roedores, aves, insetos e mel.", curiosidade: "Lontra-neotropical e irara: apesar de pertencerem ao mesmo grupo, possuem hábitos bem diferentes." },
        { nome: "Gato-mourisco", imagem: "images/mamifero/gato_mourisco.jpg", texto: "O gato-mourisco é um felino de corpo alongado e aparência diferente de outros gatos selvagens. Vive em bordas de matas, cerrados e áreas arbustivas secas. É carnívoro e caça principalmente pequenos roedores, aves e lagartos.", curiosidade: "Gato-mourisco e veado-catingueiro: o gato-mourisco é um predador, enquanto o veado-catingueiro se alimenta principalmente de vegetais e frutos." },
        { nome: "Veado-catingueiro", imagem: "images/mamifero/veado_catingueiro.jpg", texto: "O veado-catingueiro é um pequeno cervídeo que costuma ser discreto e evita locais muito abertos. Habita florestas secundárias, cerrados e capoeiras secas. Alimenta-se de folhas, ramos e frutos caídos, sendo considerado herbívoro e frugívoro.", curiosidade: "Gato-mourisco e veado-catingueiro: esses animais podem ocupar áreas de cerrado e vegetação mais seca." },
        { nome: "Tatu-galinha", imagem: "images/mamifero/tatu_galinha.jpg", texto: "O tatu-galinha é um mamífero protegido por uma carapaça e conhecido por sua capacidade de cavar. Vive em campos, savanas e bordas de matas. Sua alimentação inclui principalmente insetos, larvas e pequenos invertebrados, mas também pode consumir frutos.", curiosidade: "Tatu-canastra e tatu-galinha: ambos possuem carapaça e são excelentes escavadores." }
    ],
    aves: [
        { nome: "Tuiuiú", imagem: "images/aves/tuiuiu.jpg", texto: "O tuiuiú é uma das aves mais conhecidas do Pantanal e está muito associado às paisagens alagadas da região. Vive em lagoas temporárias, campos alagados e costuma construir seus ninhos em árvores altas. Alimenta-se de peixes, moluscos, anfíbios, répteis e insetos.", curiosidade: "Tuiuiú e arara-azul-grande: as duas aves são símbolos muito conhecidos do Pantanal. O tuiuiú está fortemente associado às áreas alagadas, enquanto a arara-azul depende das palmeiras para obter grande parte de seu alimento." },
        { nome: "Arara-azul-grande", imagem: "images/aves/arara_azul_grande.jpg", texto: "A arara-azul-grande é uma ave de grande porte, conhecida por sua plumagem azul intensa e seu forte bico. Vive principalmente em matas de galeria e regiões com palmeiras. Sua alimentação é especializada em frutos e castanhas de palmeiras, como acuri e bocaiúva.", curiosidade: "Tuiuiú e arara-azul-grande: as duas aves são símbolos muito conhecidos do Pantanal. A arara-azul depende das palmeiras para obter grande parte de seu alimento." },
        { nome: "Tucano-toco", imagem: "images/aves/tucano_toco.jpg", texto: "O tucano-toco é uma ave facilmente reconhecida pelo seu grande bico colorido. Vive em bordas de matas, cerrados e copas de árvores isoladas. É onívoro e alimenta-se de frutos, insetos, ovos e até filhotes de outras aves.", curiosidade: "Tucano-toco e cardeal-do-pantanal: apesar da diferença de tamanho, as duas aves podem ser encontradas em ambientes com vegetação próxima aos rios. O tucano possui um bico enorme em relação ao corpo, enquanto o cardeal possui um bico pequeno e adaptado para sementes e insetos." },
        { nome: "Cardeal-do-pantanal", imagem: "images/aves/cardeal_do_pantanal.jpg", texto: "O cardeal-do-pantanal é uma pequena ave de cores marcantes que costuma ser encontrada próxima à água. Vive em vegetação ribeirinha, arbustos e capoeiras. Alimenta-se principalmente de sementes, grãos e pequenos insetos.", curiosidade: "Tucano-toco e cardeal-do-pantanal: apesar da diferença de tamanho, as duas aves podem ser encontradas em ambientes com vegetação próxima aos rios." },
        { nome: "Colhereiro", imagem: "images/aves/colhereiro.jpg", texto: "O colhereiro é uma ave aquática conhecida pelo bico longo e achatado, semelhante a uma colher. Vive em lagoas rasas, banhados e áreas de lama. Alimenta-se de pequenos peixes, crustáceos e larvas aquáticas que encontra na água.", curiosidade: "Colhereiro e gavião-belo: as duas aves procuram alimento em ambientes aquáticos, mas utilizam estratégias diferentes. O colhereiro movimenta seu bico pela água rasa para encontrar pequenas presas, enquanto o gavião-belo captura peixes a partir de um poleiro." },
        { nome: "Gavião-belo", imagem: "images/aves/gaviao_belo.jpg", texto: "O gavião-belo é uma ave de rapina especializada na captura de peixes. Costuma ficar pousado em árvores próximas a rios, lagos e pântanos. Alimenta-se principalmente de peixes que captura na superfície da água.", curiosidade: "Colhereiro e gavião-belo: as duas aves procuram alimento em ambientes aquáticos. O gavião-belo captura peixes a partir de um poleiro." },
        { nome: "Carcará", imagem: "images/aves/carcara.jpg", texto: "O carcará é uma ave de rapina muito adaptável, encontrada em diferentes tipos de ambientes. Vive em campos abertos, cerrados e pastagens secas. É onívoro e também necrófago, podendo comer carniça, cobras, lagartos, insetos e pequenos roedores.", curiosidade: "Carcará e garça-branca-grande: as duas espécies são bastante adaptáveis e podem ser vistas em ambientes modificados ou naturais. O carcará possui uma dieta muito variada, enquanto a garça depende principalmente da captura de animais em áreas de água rasa." },
        { nome: "Garça-branca-grande", imagem: "images/aves/garca_branca_grande.jpg", texto: "A garça-branca-grande é uma ave aquática de pernas e pescoço longos, geralmente encontrada caminhando em águas rasas. Vive nas margens de rios, lagos, lagoas e praias de rios. Alimenta-se de peixes, sapos, lagartos e insetos aquáticos.", curiosidade: "Carcará e garça-branca-grande: enquanto o carcará tem dieta variada, a garça depende da captura de animais em áreas de água rasa." },
        { nome: "Mutum-de-penacho", imagem: "images/aves/mutum_de_penacho.jpg", texto: "O mutum-de-penacho é uma ave de grande porte que passa boa parte do tempo caminhando pelo chão das florestas. Vive em matas ciliares e florestas de galeria. Alimenta-se principalmente de frutos caídos, sementes, folhas e brotos.", curiosidade: "Mutum-de-penacho e anhuma: essas aves possuem hábitos bem diferentes. O mutum passa bastante tempo no chão da floresta procurando frutos e sementes, enquanto a anhuma está mais associada a ambientes alagados e à vegetação aquática." },
        { nome: "Anhuma", imagem: "images/aves/anhuma.jpg", texto: "A anhuma é uma ave de aparência característica, associada a ambientes alagados e com vegetação aquática. Vive em pântanos, margens de rios e lagos com plantas flutuantes. É herbívora e alimenta-se de plantas aquáticas, folhas e brotos.", curiosidade: "Mutum-de-penacho e anhuma: essas aves possuem hábitos bem diferentes. A anhuma está mais associada a ambientes alagados e à vegetação aquática." },
        { nome: "Ema", imagem: "images/aves/ema.jpg", texto: "A ema é uma grande ave que não consegue voar, mas possui pernas fortes adaptadas para correr. Vive em grandes campos abertos e savanas secas. É onívora e se alimenta de folhas, sementes, frutos, insetos e pequenos répteis.", curiosidade: "Ema e choró-do-pantanal: são aves de tamanhos completamente diferentes e ocupam ambientes distintos. A ema é uma grande corredora dos campos abertos, enquanto o choró-do-pantanal é pequeno e costuma ficar escondido na vegetação." },
        { nome: "Choró-do-pantanal", imagem: "images/aves/choró_do_pantanal.jpg", texto: "O choró-do-pantanal é uma pequena ave que vive escondida entre a vegetação densa. É encontrado principalmente em brejos com arbustos e matas de galeria alagadas. Alimenta-se de pequenos insetos e larvas que captura entre as folhas.", curiosidade: "Ema e choró-do-pantanal: são aves de tamanhos completamente diferentes. O choró-do-pantanal é pequeno e costuma ficar escondido na vegetação." },
        { nome: "Soldadinho", imagem: "images/aves/soldadinho.jpg", texto: "O soldadinho é uma ave conhecida principalmente pela aparência colorida dos machos e pelas exibições realizadas durante a reprodução. Vive em matas ciliares úmidas e perto de nascentes. Alimenta-se principalmente de pequenos frutos silvestres.", curiosidade: "Soldadinho e siriema: o soldadinho depende principalmente de frutos e vive em ambientes florestais úmidos. Já a siriema passa grande parte do tempo no chão de áreas abertas e caça animais como lagartos, cobras e pequenos roedores." },
        { nome: "Siriema", imagem: "images/aves/siriema.jpg", texto: "A siriema é uma ave de pernas longas que passa grande parte do tempo caminhando pelo chão em busca de alimento. Vive em campos secos, pastagens e cerrados abertos. É onívora e alimenta-se de serpentes, lagartos, roedores, insetos e sementes.", curiosidade: "Soldadinho e siriema: o soldadinho depende principalmente de frutos e vive em ambientes florestais úmidos. Já a siriema passa grande parte do tempo no chão de áreas abertas e caça animais como lagartos, cobras e pequenos roedores." },
        { nome: "Jaçanã", imagem: "images/aves/jacana.jpg", texto: "A jaçanã é uma ave aquática que possui dedos e unhas longos, permitindo que caminhe sobre plantas flutuantes. Vive em lagoas e corixos cobertos por aguapés e outras plantas aquáticas. É onívora e come insetos, moluscos e sementes.", curiosidade: "Jaçanã e curicaca: ambas são aves que costumam procurar alimento caminhando, mas em ambientes diferentes. A jaçanã caminha sobre plantas flutuantes na água, enquanto a curicaca procura alimento no solo." },
        { nome: "Curicaca", imagem: "images/aves/curicaca.jpg", texto: "A curicaca é uma ave de pernas longas que costuma procurar alimento caminhando pelo solo. Vive em campos secos, pastagens e praias de rios depois da vazante. Alimenta-se de gafanhotos, aranhas, centopeias, sapos e pequenas cobras.", curiosidade: "Jaçanã e curicaca: ambas são aves que costumam procurar alimento caminhando. A curicaca procura alimento no solo." },
        { nome: "Carão", imagem: "images/aves/carao.jpg", texto: "O carão é uma ave associada a ambientes alagados e possui um bico adaptado para procurar alimento. Vive em banhados, brejos, margens de lagoas e áreas úmidas. Alimenta-se principalmente de caramujos aquáticos, conhecidos como aruás.", curiosidade: "Carão e gavião-caramujeiro: as duas aves possuem uma relação muito forte com os caramujos aquáticos. O carão utiliza seu bico para retirar os caramujos, enquanto o gavião-caramujeiro possui garras e bico adaptados para capturá-los e comê-los." },
        { nome: "Gavião-caramujeiro", imagem: "images/aves/gaviao_caramujeiro.jpg", texto: "O gavião-caramujeiro é uma ave de rapina especializada em capturar caramujos aquáticos. Vive em áreas alagadas, lagoas com vegetação e canais. Sua alimentação é composta quase exclusivamente por caramujos aruás.", curiosidade: "Carão e gavião-caramujeiro: as duas aves possuem uma relação muito forte com os caramujos aquáticos. O gavião-caramujeiro possui garras e bico adaptados para capturá-los e comê-los." },
        { nome: "Cabeça-seca", imagem: "images/aves/cabeca_seca.jpg", texto: "A cabeça-seca é uma ave pernalta que costuma formar grandes grupos em áreas de água rasa. Vive em lagoas temporárias e regiões alagadas, principalmente durante períodos de seca. Alimenta-se de peixes, anfíbios e crustáceos, procurando suas presas com o bico dentro da água e do lodo.", curiosidade: "Cabeça-seca e talha-mar: as duas são aves que dependem de ambientes aquáticos para se alimentar. A cabeça-seca procura peixes e outros animais em águas rasas usando o bico, enquanto o talha-mar captura pequenos peixes voando rente à superfície da água." },
        { nome: "Talha-mar", imagem: "images/aves/talha_mar.jpg", texto: "O talha-mar é uma ave aquática facilmente reconhecida pelo formato incomum de seu bico. Vive principalmente em grandes rios e praias de areia e costuma voar muito próximo da superfície da água. Alimenta-se de pequenos peixes, capturados enquanto corta a água com a parte inferior do bico.", curiosidade: "Cabeça-seca e talha-mar: as duas são aves que dependem de ambientes aquáticos para se alimentar. O talha-mar captura pequenos peixes voando rente à superfície da água." }
    ],
    repteis: [
        { nome: "Jacaré-do-pantanal", imagem: "images/repteis_anfibios/jacare_do_pantanal.jpg", texto: "O jacaré-do-pantanal é um réptil muito comum nas áreas alagadas do Pantanal e passa grande parte da vida próximo à água. Vive em rios, corixos e lagoas permanentes ou temporárias. É carnívoro e piscívoro, alimentando-se de peixes, moluscos, aves e pequenos mamíferos.", curiosidade: "Jacaré-do-pantanal e sucuri-amarela: os dois são grandes predadores dos ambientes aquáticos do Pantanal. Apesar disso, podem ocupar posições diferentes na cadeia alimentar e até competir por algumas presas." },
        { nome: "Sucuri-amarela", imagem: "images/repteis_anfibios/sucuri_amarela.jpg", texto: "A sucuri-amarela é uma grande serpente semiaquática que passa bastante tempo dentro ou próxima da água. Habita brejos, pântanos, capinzais inundados e áreas de águas rasas. É carnívora e captura aves aquáticas, peixes, jacarés e pequenos mamíferos.", curiosidade: "Jacaré-do-pantanal e sucuri-amarela: os dois são grandes predadores dos ambientes aquáticos do Pantanal." },
        { nome: "Jiboia-constritora", imagem: "images/repteis_anfibios/jiboia_constritora.jpg", texto: "A jiboia-constritora é uma serpente conhecida por capturar suas presas por constrição. Pode viver em árvores de matas ciliares, cerrados e áreas mais secas. Alimenta-se de aves, lagartos e pequenos roedores.", curiosidade: "Jiboia-constritora e cágado-de-barbicha: enquanto a jiboia pode utilizar árvores e áreas terrestres para caçar, o cágado é muito mais ligado à água. Os dois são predadores que capturam animais menores para se alimentar." },
        { nome: "Cágado-de-barbicha", imagem: "images/repteis_anfibios/cagado_de_barbicha.jpg", texto: "O cágado-de-barbicha é uma tartaruga de água doce que passa boa parte do tempo dentro da água. Vive em rios, riachos e fundos de lagoas tranquilas. É carnívoro e se alimenta de pequenos peixes, insetos aquáticos e girinos.", curiosidade: "Jiboia-constritora e cágado-de-barbicha: enquanto a jiboia pode utilizar árvores e áreas terrestres para caçar, o cágado é muito mais ligado à água." },
        { nome: "Jabuti-piranga", imagem: "images/repteis_anfibios/jabuti_piranga.jpg", texto: "O jabuti-piranga é um réptil terrestre de movimentos lentos e protegido por uma carapaça resistente. Vive em matas secas, capoeiras e cerradões. É onívoro e come frutos caídos, folhas, flores, cogumelos e, ocasionalmente, carniça.", curiosidade: "Jabuti-piranga e teiú-da-frente-branca: ambos são répteis terrestres com uma alimentação bastante variada. O jabuti costuma consumir muitos vegetais e frutos, enquanto o teiú também caça pequenos animais e pode consumir carniça." },
        { nome: "Teiú-da-frente-branca", imagem: "images/repteis_anfibios/teiu_da_frente_branca.jpg", texto: "O teiú-da-frente-branca é um lagarto grande e ativo, conhecido por sua capacidade de explorar diferentes ambientes em busca de alimento. Vive em campos abertos, cerrados e bordas de matas. É onívoro e pode comer ovos, insetos, pequenos roedores, aves, frutas e carniça.", curiosidade: "Jabuti-piranga e teiú-da-frente-branca: ambos são répteis terrestres com uma alimentação bastante variada. O teiú também caça pequenos animais e pode consumir carniça." },
        { nome: "Cobra-coral-pantaneira", imagem: "images/repteis_anfibios/cobra_coral_pantaneira.jpg", texto: "A cobra-coral-pantaneira é uma serpente que costuma permanecer escondida entre folhas, troncos e no solo. Vive principalmente em áreas de floresta seca, utilizando o subsolo e a serrapilheira como abrigo. É carnívora e alimenta-se principalmente de pequenas serpentes e lagartos que vivem no solo.", curiosidade: "Cobra-coral-pantaneira e jararaca-boca-de-sapo: as duas são serpentes que utilizam ambientes de vegetação e solo para se esconder. Porém, enquanto a jararaca possui veneno usado para capturar suas presas, a cobra-coral-pantaneira caça principalmente outras serpentes e pequenos lagartos." },
        { nome: "Jararaca-boca-de-sapo", imagem: "images/repteis_anfibios/jararaca_boca_de_sapo.jpg", texto: "A jararaca-boca-de-sapo é uma serpente peçonhenta que utiliza a camuflagem para permanecer escondida no ambiente. Vive em áreas de transição, capoeiras e matas secas próximas de locais úmidos. É carnívora e alimenta-se de pequenos roedores, lagartos e anfíbios.", curiosidade: "Cobra-coral-pantaneira e jararaca-boca-de-sapo: as duas são serpentes que utilizam ambientes de vegetação e solo para se esconder. A jararaca possui veneno usado para capturar suas presas." },
        { nome: "Perereca-verde-pantaneira", imagem: "images/repteis_anfibios/perereca_verde_pantaneira.jpg", texto: "A perereca-verde-pantaneira é um anfíbio arborícola que costuma ficar sobre plantas próximas à água. Vive em vegetação flutuante, arbustos de lagoas e brejos. É insetívora e alimenta-se de moscas, mosquitos e pequenos besouros.", curiosidade: "Perereca-verde-pantaneira e sapo-cururu: os dois são anfíbios que dependem de ambientes úmidos, mas possuem estilos de vida diferentes. A perereca costuma ficar sobre a vegetação próxima da água, enquanto o sapo-cururu passa mais tempo no solo." },
        { nome: "Sapo-cururu", imagem: "images/repteis_anfibios/sapo_cururu.jpg", texto: "O sapo-cururu é um anfíbio terrestre bastante adaptável e pode ser encontrado tanto em áreas naturais quanto próximas de habitações. Vive em locais úmidos, margens de rios e ambientes terrestres. Alimenta-se principalmente de insetos, mas também pode capturar aranhas, escorpiões e lesmas.", curiosidade: "Perereca-verde-pantaneira e sapo-cururu: os dois são anfíbios que dependem de ambientes úmidos. O sapo-cururu passa mais tempo no solo." },
        { nome: "Mussurana ou cobra-preta", imagem: "images/repteis_anfibios/mussurana.jpg", texto: "A mussurana é uma serpente conhecida por sua capacidade de caçar outras serpentes. Vive principalmente no solo de matas ciliares e em áreas arbustivas úmidas. É carnívora e alimenta-se de outras serpentes, inclusive algumas espécies venenosas.", curiosidade: "Mussurana e calango-verde: ambos são predadores de pequenos animais, mas pertencem a grupos diferentes. A mussurana é uma serpente especializada em capturar outras serpentes, enquanto o calango-verde procura principalmente insetos." },
        { nome: "Calango-verde", imagem: "images/repteis_anfibios/calango_verde.jpg", texto: "O calango-verde é um lagarto ativo que costuma passar bastante tempo procurando alimento em locais ensolarados. Vive em áreas abertas, solos arenosos e bordas de estradas. É insetívoro e alimenta-se de besouros, grilos, aranhas e larvas.", curiosidade: "Mussurana e calango-verde: ambos são predadores de pequenos animais. O calango-verde procura principalmente insetos." },
        { nome: "Tartaruga-da-amazônia", imagem: "images/repteis_anfibios/tartaruga_da_amazonia.jpg", texto: "A tartaruga-da-amazônia é uma grande tartaruga de água doce que passa grande parte da vida nos rios. Habita grandes rios calmos e utiliza praias arenosas para colocar seus ovos. É principalmente herbívora, mas também pode consumir peixes mortos, alimentando-se de frutos, sementes e folhas.", curiosidade: "Tartaruga-da-amazônia e cobra-d'água: as duas estão associadas aos rios e ambientes de água doce. A tartaruga utiliza as praias de areia para colocar seus ovos, enquanto a cobra-d'água procura suas presas dentro da própria água." },
        { nome: "Cobra-d'água", imagem: "images/repteis_anfibios/cobra_dagua.jpg", texto: "A cobra-d'água é uma serpente adaptada à vida em ambientes de água doce e possui grande habilidade para nadar. Vive em rios, corixos e outros ambientes aquáticos. Alimenta-se principalmente de pequenos peixes, girinos e rãs.", curiosidade: "Tartaruga-da-amazônia e cobra-d'água: as duas estão associadas aos rios e ambientes de água doce. A cobra-d'água procura suas presas dentro da própria água." },
        { nome: "Cobra-cipó", imagem: "images/repteis_anfibios/cobra_cipo.jpg", texto: "A cobra-cipó é uma serpente de corpo fino e alongado, adaptada a se movimentar entre galhos e arbustos. Vive em matas ciliares e cerrados, principalmente sobre a vegetação. É carnívora e alimenta-se principalmente de rãs, pererecas e pequenos lagartos.", curiosidade: "Cobra-cipó e lagarto-de-parede: ambos conseguem explorar espaços acima do solo, mas de maneiras diferentes. A cobra-cipó se movimenta pelos galhos e arbustos, enquanto o lagarto-de-parede pode subir em troncos, rochas e paredes." },
        { nome: "Lagarto-de-parede ou taruíra", imagem: "images/repteis_anfibios/taruíra.jpg", texto: "O lagarto-de-parede é um pequeno réptil muito adaptado à presença humana e costuma ser visto em paredes e construções. Vive em troncos, rochas e construções. É insetívoro e alimenta-se de mariposas, aranhas, moscas e baratas.", curiosidade: "Cobra-cipó e lagarto-de-parede: ambos conseguem explorar espaços acima do solo. O lagarto-de-parede pode subir em troncos, rochas e paredes." },
        { nome: "Falsa-coral", imagem: "images/repteis_anfibios/falsa_coral.jpg", texto: "A falsa-coral é uma serpente que possui padrões de cores que podem lembrar os de corais verdadeiras. Vive no chão de florestas secas, cerrados e pastagens. É carnívora e alimenta-se principalmente de pequenos roedores e lagartos.", curiosidade: "Falsa-coral e rã-pimenta: apesar de serem predadores, possuem estratégias diferentes para conseguir alimento. A falsa-coral caça principalmente pequenos vertebrados, enquanto a rã-pimenta captura diversos animais que consegue engolir." },
        { nome: "Rã-pimenta", imagem: "images/repteis_anfibios/ra_pimenta.jpg", texto: "A rã-pimenta é um anfíbio de grande porte e possui hábitos principalmente terrestres. Vive nas margens de lagoas, brejos e tocas úmidas no solo. É carnívora e pode comer insetos, outras rãs, pequenos roedores e até filhotes de cobras.", curiosidade: "Falsa-coral e rã-pimenta: apesar de serem predadores, possuem estratégias diferentes para conseguir alimento. A rã-pimenta captura diversos animais que consegue engolir." },
        { nome: "Perereca-assobiadora", imagem: "images/repteis_anfibios/perereca_assobiadora.jpg", texto: "A perereca-assobiadora é um pequeno anfíbio encontrado principalmente em áreas abertas que ficam alagadas durante determinados períodos do ano. Vive em campos gramados com alagamento temporário. É insetívora e alimenta-se de pequenos insetos voadores e cupins.", curiosidade: "Perereca-assobiadora e jacaretinga: as duas dependem de ambientes que possuem água, mas de formas diferentes. A perereca aproveita áreas que ficam temporariamente alagadas para viver e se reproduzir, enquanto o jacaretinga permanece associado a ambientes de água doce mais permanentes." },
        { nome: "Jacaretinga", imagem: "images/repteis_anfibios/jacaretinga.jpg", texto: "O jacaretinga é um pequeno crocodiliano que prefere ambientes de água doce calmos e rasos. Vive em canais fluviais menores e áreas de águas tranquilas. É piscívoro e carnívoro, alimentando-se de pequenos peixes, caranguejos e insetos.", curiosidade: "Perereca-assobiadora e jacaretinga: as duas dependem de ambientes que possuem água, mas de formas diferentes. O jacaretinga permanece associado a ambientes de água doce mais permanentes." }
    ]
};

// ==========================================
// FUNÇÃO PARA CRIAR OS CARDS (FOTO + TEXTO EM ZIG-ZAG)
// ==========================================
function criarCards(categoria, containerId) {
    const container = document.getElementById(containerId);
    const animais = dadosAnimais[categoria];

    // Se a pasta da imagem não existir, mostra um espaço reservado
    const pastaBase = categoria === 'mamiferos' ? 'images/mamifero' : (categoria === 'aves' ? 'images/aves' : 'images/repteis_anfibios');
    
    animais.forEach((animal) => {
        const caminhoImagem = `${pastaBase}/${animal.imagem}`;
        const imagemHTML = `<img src="${caminhoImagem}" alt="${animal.nome}" onerror="this.parentElement.innerHTML='<div style=\'height:100%; display:flex; align-items:center; justify-content:center; background:#d4d9bd; color:#3d4d36; font-weight:bold;\'>Imagem em breve</div>'">`;

        const cardHTML = `
            <div class="card-animal-zigzag" onclick="atualizarCuriosidade('${animal.nome}', '${animal.curiosidade.replace(/'/g, "\\'")}')">
                <div class="foto-col">
                    <div class="card-imagem">${imagemHTML}</div>
                </div>
                <div class="texto-col">
                    <div class="titulo-com-icone">
                        <div class="icone-folha">
                            <svg viewBox="0 0 24 24" class="svg-icon" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                <path d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z"/>
                                <path d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12"/>
                            </svg>
                        </div>
                        <h3>${animal.nome}</h3>
                    </div>
                    <p>${animal.texto}</p>
                </div>
            </div>
        `;

        container.innerHTML += cardHTML;
    });
}

// ==========================================
// FUNÇÃO PARA ATUALIZAR A CURIOSIDADE NA COLUNA DIREITA
// ==========================================
function atualizarCuriosidade(nome, curiosidade) {
    const curiosidadeTexto = document.getElementById('curiosidade-fixa-texto');
    curiosidadeTexto.innerHTML = `
        <h4 style="color: var(--verde-escuro); font-size: 20px; margin-bottom: 10px; border-bottom: 2px solid var(--verde-medio); padding-bottom: 5px;">${nome}</h4>
        <p>${curiosidade}</p>
    `;
}

// ==========================================
// INICIALIZAÇÃO E NAVEGAÇÃO
// ==========================================
document.addEventListener('DOMContentLoaded', () => {
    // Carrega os cards
    criarCards('mamiferos', 'container-mamiferos');
    criarCards('aves', 'container-aves');
    criarCards('repteis', 'container-repteis');

    // Lógica de troca de telas
    const navLinks = document.querySelectorAll('.nav-link');
    const sections = document.querySelectorAll('.content-section');

    navLinks.forEach(link => {
        link.addEventListener('click', function(e) {
            e.preventDefault();

            navLinks.forEach(l => l.classList.remove('active'));
            this.classList.add('active');

            const targetId = this.getAttribute('data-target');

            sections.forEach(section => section.classList.remove('active-section'));

            const targetSection = document.getElementById(targetId);
            if (targetSection) {
                targetSection.classList.add('active-section');
            }

            window.scrollTo({ top: 0, behavior: 'smooth' });
        });
    });
});